name: Demos
on:
  workflow_dispatch:
  pull_request:
    types: [labeled]
jobs:
  build-and-run-demos:
    if: ${{ github.event.label.name == 'check-demos' }}
    name: Build and Run Demos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: v1.17
      - run: make build

      - name: Install latest version of Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          sudo cp kind /usr/local/bin
      - name: Install dependencies before running demos
        run: |
          sudo apt-get install pv
      - name: Test Demos
        run: |
          mkdir tests
          cd tests
          ../contrib/demo/runDemos.sh -t
      - name: Archive Demo test results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: demo-tests
          path: tests/**/*.log
